### ISSUE TITLE
BiblioMigrateEntries should extend DynamicMigration

### ISSUE THREAD

**Issue by amitaibu** [Gizra/biblio#113]
For reference see

`og_ui_migrate_api()` and `OgUiPopulateField` (which extends `DynamicMigration` and implements `generateMachineName()`).

**Comment by shushu** [comment]
@amitaibu inside migration.inc I found:
- @deprecated - This class is no longer necessary, inherit directly from
-  Migration instead.

What do you want me to do with it ?

**Comment by amitaibu** [comment]
@shushu We still need to make the class dynamic, so you'll need to figure out the new way of doing that with Migrate 2.6

**Comment by shushu** [comment]
WIP. Updates:
- generateMachineName() is deprecated as well. No need for it.
- As discussed, Biblio 3.x will support only Migrate 2.6 and above. I think we should give a message to the site owner saying so.

**Comment by shushu** [comment]
@amitaibu question - do we want to try and attach fields automatically to biblio types during migrate ?

**Comment by amitaibu** [comment]
no, currently do it manually via ui - it will be  follow up.

**Comment by shushu** [comment]
![biblio 3 x migrate on hwpi os](https://f.cloud.github.com/assets/99186/1867941/0dd19a4e-785d-11e3-916f-43289b6ad9ce.png)
