### ISSUE TITLE
Endnote XML import not working on hostgator

### ISSUE THREAD

**Issue by guidout** [Gizra/biblio#169]
I am using hostgator for hosting a website and when I import all my bibliography I just get a bunch of almost empty nodes. There are just the authors, everything else is empty, including the Title.
I extensively tested my library, XML files, etc. locally.
I hope this has an explanation.

Thank you,
Guido

**Comment by amitaibu** [comment]
Are you using the 3.x version of Biblio?

**Comment by guidout** [comment]
I'm using 7.x-1.0-rc7

**Comment by amitaibu** [comment]
Then you should report on drupal.org issue queue.

**Comment by guidout** [comment]
really sorry!
